baseURL = "https://josephcosentino.me/"
languageCode = "en"
pluralizeListTitles = false

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 2
  [[menu.main]]
    name = "Resume"
    url = "/resume"
    weight = 3
