baseURL = "https://josephcosentino.me/"
languageCode = "en"
sectionPagesMenu = 'main'

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Resume"
    url = "/resume"
    weight = 1
