language: node_js
node_js:
- node
before_script:
- npm install -g gulp
script: gulp build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "josephcosentino.me"
  skip_cleanup: true
  region: "us-east-1"

env:
  global:
  - secure: TbhXbimzWPLtJCMUf7TrWEMoSCai3vpqM0Z8IZVsmkToCpNW/QFKFKt4GINlVqWsqc70asbimnxjfqNx2kpt8KfTMgZINwW+oPUdiykMLegfhvoGpP7AWdsfLKaYohup+gW8ZACV6FnSw+ATun/Ua0IswTdix8liUmWI98HleVlpvW4xlc7uM5sYzxojfCycV0ALFKma/ylWrbUO8n04OyOvROvWriN7qoqqjVNoSp3hjuZ8lNM50kaitQOlnp6n6ZbldVQtD0FTw+bq+xHWajUwpse4HqEbC1QYWVFfvR3ayEW6g2RZaa2ICACudWnWvP311le4MlCnVMFnb72AAv41bi7cYobuMdbVbFU4AUebz8eCgyOOoeH7kps4ITKNDjpT4h+ryjJz1eAzGOMgjFLqeE9dCydhr9RpJnAQ2muUcR2IuKzXTZRr6dn1HsOtI3ahAeKCVdmJwzH331eZmjxY4LfgZbQnt0/mWOyP14Tgnqhm/LMTCKUf/RllgQIVPRv2njUc6u+B1O7G87j1jk1HjevrVYDCpBgQQc4/aTyge4PNCScBNrnO+2Ybi1p991JtfNi6s7dBTdxFmegQN+8Lf+BMLl51GuYcUdpH5ZyvVQjMLADYXf5Gxy0V6nLFE6yjuawzZmWWb77hkgOqVd0DNJagw8zI3abnlWEB+c8=
  - secure: ooFTG0B7udNnpZUnGDrJjg4EHT2kkWg9FWty4CXI7dIpWHNmZ9ypuHgLIuo9Y2EgMXo41tCyeiy0oim4L+sWHB8Ducq8GjfjnBJYxApcse5ugHkXcQj/E3MuRdwCRCT+UHkpVh48woWLYegrPGyTF+ts3PcO9tLorABs28nGMm6pIqvLi4n6PcfR+UshvGfxO0lPqxPf+Tex0PzbVrPqp62HWo4LmLIMsfwkgKMCebLKK7Wpt6o4uM+DlAzEomCG+wb6eOBCWDuFDmzpZq87goGdTgRlcDCGmwbxusmG4WtOqeHI/ZHCvLWV20XUq2mmjzzzTE/waadKhpYzBhrndPvMrRJginRZ52dR9ASl35tbknl9B4i7Dm5+GXRplBJykhfbhwPmN/6Fz7UETrHbcFUHkdcNfhXbmWvjJIVZGk/pB5MCeX3T0XmhZcC92Z23vNcvKYEPJjqPpX+eD61QM5z6vTwGs/RLxk4YUQbOm+hazCUV1xfNoO01MLNidQ0LZnXq9Xm46ftVBOrMvn87cmHY7DryNcyJgMPfhEDwNF+EQjDV/+KsK30lJg6neDzHDvDu1jJNk/W1UZ2tBDcWRjR1dlxZrc8QvQQ7z6LaBkMtYnIQLn+zmNj60NYy3tsV8C7xW32RloTMY6qVD7oJVF/SAH3P3yYGlwg8IENO9ko=
